const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const app = express();
const PORT = process.env.PORT || 3000;
const MailerRoute = require("./mailer");
app.use(bodyParser.json());
app.use(cors());
app.use(MailerRoute);
app.listen(PORT, () => console.log(`server is running on port ${PORT}`));
